on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: before
        run: ls

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: after
        run: ls

      - name: Login to Docker Hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

       
      - name: Pull OpenJDK image manually
        run: docker pull openjdk:17-jdk

      - name: building docker image
        run: docker build --pull -t ${{ secrets.DOCKER_USERNAME }}/mahmoudgalal2023040383 .

      - name: pushing to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mahmoudgalal2023040383